# see _data/meta.yml (so you don't have to restart jekyll to see changes)
baseurl: ''
url: http://256klabs.com
permalink: pretty
sort_by: year, month
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
include: ['_pages']

collections:
  docs:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "docs"

  - scope:
      path: ""
      type: "projects"
    values:
      layout: "projects"