# see _data/meta.yml (so you don't have to restart jekyll to see changes)
baseurl: '/256klabs'
url: http://256klabs.com/
permalink: pretty
sort_by: year, month
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
include: ['_pages']
